### PR TITLE
Adopt project

### PR DESCRIPTION
**Pull request by NightTsarina**
* 18f6f02 - Add myself as author
* 457e5ec - Remove last reference to @brandond repo

### CODE REVIEW

**Review by dswarbrick — APPROVED** [review]

**Comment by brandond** [comment]
Do you want me to just transfer the original repo somewhere? Glad to acknowledge a more active fork as the primary.

**Comment by NightTsarina** [comment]
> Do you want me to just transfer the original repo somewhere? Glad to acknowledge a more active fork as the primary.

Hi @brandond, thanks for getting in touch! I should have probably sent you an email about this, sorry about that...

If you are not planning on continuing work on the project, I would be glad to take it as primary maintainer. I suppose the best would be a repo transfer (after I rename this fork)?

@dswarbrick would you be interested in "officially" co-maintaining? Any thoughts on repo location?

**Comment by dswarbrick** [comment]
@NightTsarina I'm not likely to be an active user of this exporter. I just have a bad habit of adopting stray Prometheus projects, and by sheer dumb luck, I still have the Devolo dLAN 200 AVplus kit that I acquired about 12 years ago. I am happy to donate some time to it now and then, so if that makes me an official co-maintainer, so be it.

**Comment by NightTsarina** [comment]
> @NightTsarina I'm not likely to be an active user of this exporter. I just have a bad habit of adopting stray Prometheus projects, and by sheer dumb luck, I still have the Devolo dLAN 200 AVplus kit that I acquired about 12 years ago. I am happy to donate some time to it now and then, so if that makes me an official co-maintainer, so be it.

Fair enough. I thought you used homeplug adaptors regularly too. No need to commit to anything, I really appreciate any help.

**Comment by brandond** [comment]
@NightTsarina I'm not sure how to go about transferring the project to you. I think that if you rename this repo, I can transfer mine to you under this same name? Or if you want to create an org for it and give me access, I can transfer it there.

**Comment by NightTsarina** [comment]
Sorry @brandond, I had missed your reply..

> @NightTsarina I'm not sure how to go about transferring the project to you. I think that if you rename this repo, I can transfer mine to you under this same name? Or if you want to create an org for it and give me access, I can transfer it there.

I have just realised there is a problem that will prevent the transfer: one of the pre-requisites is "The target account must not have a repository with the same name, or a fork in the same network."  ([source](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository))

So I have created a support ticket to detach the fork, and also to ask how to best handle this. I will keep you updated

**Comment by NightTsarina** [comment]
@brandond Github support replied:

> I am happy to help you with this by rerouting your fork repo as the parent repository but since you do not own the repo, we'll first need permission from the owner of the parent repository in order to do this.
>  
> If you could CC them and have them respond to this email, I'll be able to process your request as soon as I get their approval.

I will send you now a copy of the email, so you can reply and complete this, if you agree.

**Comment by NightTsarina** [comment]
I also added you as collaborator, in case you ever feel like working on this again :)

**Comment by brandond** [comment]
I've accepted the invite and responded to the email from GH support, let me know if you need anything else.

**Comment by NightTsarina** [comment]
@brandond It seems it is all done. Thanks a lot for your help and all the code!

**Comment by dswarbrick** [comment]
I second that. Thanks @brandond for bringing homeplug_exporter into the world. We'll take good care of it.

**Comment by brandond** [comment]
Good luck! This was literally the first thing I ever wrote in golang so I'm sorry for whatever problems I left behind.

I'm no longer using my plugs but I do still have them in a box somewhere if you need another tester for anything.

**Comment by NightTsarina** [comment]
> Good luck! This was literally the first thing I ever wrote in golang so I'm sorry for whatever problems I left behind.

Don't worry about it, you should see how my old perl code looked back in the day!! I hope this helps me learn some golang, because up to now I have only done patches and very small changes..

> I'm no longer using my plugs but I do still have them in a box somewhere if you need another tester for anything.

Thank you very much for the offer!

**Pull request merged**
